#!/bin/sh
if [ "$2" = '-m' ]; then
  printf 'NPU ID  Chip ID  Chip Logic ID  Chip Name\n4 0 2 Ascend910B\n4 1 3 Ascend910B\n4 2 - Mcu\n'
else
  echo "$*" >> "$TEST_ROOT/npu-queries"
  echo 'No running processes found in NPU 4'
fi
